env:
  id: CartPole-v1
  type: classic
  atari:
    screen_size: 84
    frame_skip: 4
    term_on_life_loss: false
    grayscale: true
    noop_max: 30
    fire_reset: true
    episodic_life: true
  reward: sign
  time_limit: 108e3
  stack: 4
total_steps: 500e3
lr: 2.5e-4
opt_eps: 1e-5
train_envs: 4
steps_per_epoch: 128
gamma: 0.99
gae_lambda: 0.95
update_epochs: 4
update_batch: 128
adv_norm: true
env_workers: 4
val_episodes: 16
device: cuda
clip_coeff: 0.1
clip_vloss: true
ent_coeff: 1e-2
vf_coeff: 0.5
clip_grad: 0.5
log_every: 128
val_every: 10e3
decorrelate: false
share_encoder: false
custom_init: true
seed: 42