device: cuda
buffer:
  capacity: 100e3
  prefill: 1e3
env:
  type: gym
  atari:
    env_id: ALE/Pong-v5
    noop_max: 30
    frame_skip: 4
    term_on_life_loss: false
    obs_type: grayscale
    screen_size: 84
    fire_reset: true
    time_limit: 108e3
    stack: 4
  gym:
    env_id: CartPole-v1
  dmc:
    env_id: Walker2d-v1
batch_size: 64
seq_len: 7
total_steps: 1e5
env_steps: 512
opt_steps: 32
opt:
  type: adam
  lr: 1e-4
  eps: 1e-5
cem:
  pop: 128
  elites: 16
  horizon: 8
  niters: 4
profiler:
  enabled: false
  start:
    step: 20e3
  duration:
    step: 16
