[tool.poetry]
name = "rsrch"
version = "0.1.0"
description = ""
authors = ["vitreusx <jakub_bednarz@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
poetry = "1.3.2"
ipykernel = "^6.21.2"
ipywidgets = "^8.0.4"
setuptools = "*"
conda-lock = "*"
torch = "~2.0"
torchvision = "~0.15"
box2d-py = {path = "ext/box2d-py"}
gymnasium = {version = "^0.28.1", extras = ["accept-rom-license", "all"]}
tensordict = "^0.1.0"
tensorboard = "^2.12.2"
torch-tb-profiler = "^0.4.1"
colorama = "*"
moviepy = "*"
python-slugify = "*"
lightning = "*"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.22.0"
black = {version = "^23.3.0", extras = ["jupyter"]}
nbconvert = "^7.3.1"


[tool.poetry.group.conda.dependencies]
attrs = "22.2.0"
boltons = "23.0.0"
brotlipy = "0.7.0"
cachecontrol = "0.12.11"
certifi = "2022.12.7"
cffi = "1.15.1"
charset-normalizer = "3.1.0"
cleo = "2.0.1"
colorama = "0.4.6"
conda-package-streaming = "0.7.0"
crashtest = "0.4.1"
cryptography = "40.0.1"
distlib = "0.3.6"
dulwich = "0.20.50"
filelock = "3.11.0"
html5lib = "1.1"
idna = "3.4"
importlib-metadata = "4.13.0"
importlib-resources = "5.12.0"
jeepney = "0.8.0"
jaraco-classes = "3.2.3"
jsonschema = "4.17.3"
keyring = "23.13.1"
pexpect = "4.8.0"
packaging = "23.0"
msgpack = "1.0.5"
lockfile = "0.12.2"
ptyprocess = "0.7.0"
numpy = "1.24.2"
poetry = "1.3.2"
pkginfo = "1.9.6"
platformdirs = "2.6.2"
more-itertools = "9.1.0"
poetry-core = "1.4.0"
poetry-plugin-export = "1.3.0"
pyrsistent = "0.19.3"
pycparser = "2.21"
ruamel-yaml = "0.17.21"
ruamel-yaml-clib = "0.2.7"
requests-toolbelt = "0.10.1"
rapidfuzz = "2.15.0"
six = "1.16.0"
secretstorage = "3.3.3"
tomli = "2.0.1"
zstandard = "0.19.0"
shellingham = "1.5.1"
requests = "2.28.2"
tomlkit = "0.11.7"
typing-extensions = "4.5.0"
zipp = "3.15.0"
tqdm = "4.65.0"
urllib3 = "1.26.15"
trove-classifiers = "2023.3.9"
virtualenv = "20.21.0"
webencodings = "0.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"