[tool.poetry]
name = "rsrch"
version = "0.1.0"
description = ""
authors = ["vitreusx <jakub_bednarz@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
poetry = "1.3.2"
ipykernel = "^6.21.2"
ipywidgets = "^8.0.4"
setuptools = "*"
conda-lock = "*"
torch = "~2.0"
torchvision = "~0.15"
box2d-py = {path = "ext/box2d-py"}
gymnasium = {version = "^0.28.1", extras = ["accept-rom-license", "all"]}
tensorboard = "^2.12.2"
torch-tb-profiler = "^0.4.1"
colorama = "*"
moviepy = "*"
python-slugify = "*"
lightning = "*"
mujoco-py = "^2.1.2.14"
patchelf = "^0.17.2.1"
mujoco = "<=2.3.3"
ptflops = "^0.7"
h5py = "^3.8.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.22.0"
black = {version = "^23.3.0", extras = ["jupyter"]}
nbconvert = "^7.3.1"
pylint = "^2.17.4"
isort = ">=5"

[tool.poetry.group.conda]
optional = true

[tool.poetry.group.conda.dependencies]
requests = "2.29.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.pylint.format]
max-line-length = "88"