[tool.poetry]
name = "rsrch"
version = "0.1.0"
description = ""
authors = ["vitreusx <jakub_bednarz@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
gymnasium = {extras = ["accept-rom-license", "all"], version = "^0.27.1"}
swig = "4.1.1"
box2d-py = "2.3.5"
poetry = "1.3.2"
dvc = ">=2.0.0"
ipykernel = "^6.21.2"
black = "^23.1.0"
ipywidgets = "^8.0.4"
setuptools = "*"
conda-lock = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
