[tool.poetry]
name = "rsrch"
version = "0.1.0"
description = ""
authors = ["vitreusx <jakub_bednarz@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.*"
poetry = "^1.5"
ipykernel = "^6.22.0"
ipywidgets = "^8.0.4"
setuptools = "*"
tensorboard = "^2.12.2"
torch-tb-profiler = "^0.4.1"
colorama = "*"
moviepy = "*"
python-slugify = "*"
patchelf = "^0.17.2.1"
mujoco = "<=2.3.3"
ptflops = "^0.7"
h5py = "^3.8.0"
sympy = "^1.12"
torch = {version = "2.1.*", platform = "linux", source = "torch"}
torchvision = {version = "0.16.*", platform = "linux", source = "torch"}
gymnasium = { version = "0.26.*", extras = ["accept-rom-license", "all"] }
poethepoet = "^0.21.0"
wandb = "^0.15.5"
plotly = "^5.15.0"
dacite = "^1.8.1"
mako = "^1.2.4"
envpool = "^0.8.3"
cython = "<3"
box2d-py = { path = "ext/box2d-py" }
black = { version = "^23.3.0", extras = ["jupyter"] }
nbconvert = "^7.3.1"
pylint = "^2.17.4"
isort = ">=5"
poetry-plugin-export = "^1.6.0"
ray = "^2.9.0"
lightning = "^2.1.3"
ruamel-yaml = "^0.18.5"

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poe.tasks.fix-torch]
help = "Install CUDA version of torch*. Due to issues with torch's packaging, it cannot really be done directly in poetry."
shell = """
for PKG in torch torchvision; do
  VER=$(pip freeze \
    | grep -E "^${PKG}==[^ ]*" -o \
    | sed -E "s/${PKG}==([0-9\\.]*).*/\\1/")
  if [ -n "${VER}" ]; then
    pip install -U ${PKG}==${VER}+${tag} \
      --index-url "https://download.pytorch.org/whl/${tag}"
  fi
done
"""
args = [{ name = "tag", default = "cu121" }]

[tool.poe.tasks.fix-opencv]
help = "Replace opencv-python with headless version."
shell = """
VER=$(pip freeze \
  | grep -E "opencv-python==[^ ]*" -o \
  | sed -E 's/opencv-python==(.*)/\\1/')

if [ -n "${VER}" ]; then
  pip uninstall -y opencv-python opencv-python-headless
  pip install -U opencv-python-headless==${VER}
fi
"""

[build-system]
requires = ["poetry-core>=1.5"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.pylint.format]
max-line-length = "88"

[tool.pylint."MESSAGES CONTROL"]
disable = "invalid-name,missing-module-docstring"

[tool.pylint.TYPECHECK]
generated-members = "numpy.*, torch.*, np.*"
