line-length = 88
indent-width = 4
target-version = "py310"

[format]
docstring-code-format = true

[lint]
select = ["C", "E", "F"]
ignore = [
    "E731", # Lambda assignment
    "C416", # Unnecessary dict comprehension
    "C901" # ... is too complex
]
exclude = ["ext/*"]