# yaml-language-server: $schema=config.schema.json
seed: 0
compute_dtype: float16
create_exp_commit: false
batch_size: 16
val_batch_size: ~
log_every: { n: 4, of: step }
val_every: { n: 1, of: epoch }
save_every: ~
lr: 3e-4
