faster:
  random.deterministic: false
pong:
  env.atari.env_id: ALE/Pong-v5
dominik:
  num_envs: 64
  opt:
    batch_size: 256
    sched:
      every: ['${opt.batch_size/8}', agent_step] # replay ratio = 8
      iters: 1
  nets:
    encoder: impala[large,2]
    spectral_norm: last
    polyak: {every: [32e3, env_step], tau: 0.0}
  distq.enabled: false
  total_env_steps: 40e6
  data.parallel: true
der:
  warmup: 6.4e3
  total_env_steps: 400e3
  data.slice_len: 20
  opt:
    sched: {every: [1, agent_step]}
    batch_size: 32
