requires:
  exec_env:
    type: node
    node:
      device: cuda
random:
  seed: 42
  deterministic: true
env:
  type: atari
  atari:
    env_id: ALE/Alien-v5
    screen_size: 84
    frame_skip: 4
    obs_type: grayscale
    noop_max: 30
    fire_reset: true
    term_on_life_loss: true
    time_limit: 108e3
    stack: 4
    use_envpool: true
distq:
  enabled: true
  num_atoms: 51
  v_min: -10.0
  v_max: +10.0
nets:
  encoder: nature
  hidden_dim: 256
  dueling: true
  polyak: {every: {n: 32e3, of: env_step}, tau: 0.0}
  spectral_norm: none
data:
  buf_cap: 1e6
  slice_len: 3
  prefetch_factor: 2
  parallel: false
total: {n: 250e6, of: env_step}
num_envs: 1
expl:
  noisy: true
  sigma0: 0.5
  factorized: true
  eps: 0.0
aug:
  rew_clip: [-1.0, 1.0]
prioritized:
  enabled: true
  prio_exp: 0.5
  is_coef_exp: {desc: 'linear(0.4, 1.0, ${total.n})', of: '${total.of}'}
warmup: 80e3
val:
  sched: {every: {n: 128e3, of: env_step}}
  episodes: 32
  envs: ${.episodes}
opt:
  dtype: float32
  sched: {every: {n: 4, of: agent_step}}
  batch_size: 32
  optimizer:
    type: adam
    lr: 2.5e-4
    eps: ${5e-3 / opt.batch_size}
  grad_clip: 10.0
log: {every: {n: 16, of: opt_step}}
gamma: 0.99
double_dqn: true
resume: null