faster:
  random.deterministic: false
dominik:
  num_envs: 64
  opt:
    batch_size: 256
    sched:
      every: ['${opt.batch_size/8}', agent_step] # replay ratio = 8
      iters: 1
  nets:
    encoder: impala[large,2]
    spectral_norm: last
    polyak: {every: [32e3, env_step], tau: 0.0}
  distq.enabled: false
  prioritized.enabled: false
  total_env_steps: 40e6
  data.parallel: true
der:
  warmup: 1.6e3
  data.slice_len: 20
  opt:
    sched: {every: 1}
    batch_size: 32