faster:
  random.deterministic: false
no_noisy:
  expl:
    noisy: false
    eps: {desc: 'linear(1.0, 0.1, ${total.n})', of: '${total.of}'}
pong:
  env.atari.env_id: ALE/Pong-v5
dominik:
  $extends: [faster, no_noisy]
  num_envs: 64
  opt:
    batch_size: 256
    sched:
      every: {n: '${opt.batch_size/8}', of: agent_step} # replay ratio = 8
      iters: 1
  nets:
    encoder: impala[large,2]
    # spectral_norm: last
    polyak: {every: {n: 32e3, of: env_step}, tau: 0.0}
  distq.enabled: false
  total: {n: 40e6, of: env_step}
  # data.parallel: true
der:
  $extends: [faster, no_noisy]
  warmup: {n: 6.4e3, of: env_step}
  total: {n: 400e3, of: env_step}
  data:
    slice_len: 20
  opt:
    sched: {every: {n: 1, of: agent_step}}
    batch_size: 32
sample:
  resume: 'runs/rainbow/ALE-Alien-v5__2024-04-05_06-40-37/ckpts/env_step=6864128-val_ret=1579.06.pth'
  mode: sample
  total: {n: 1e6, of: env_step}