faster:
  random.deterministic: false
pong:
  env.atari.env_id: ALE/Pong-v5
dominik:
  num_envs: 64
  opt:
    batch_size: 256
    sched:
      every: {n: '${opt.batch_size/8}', of: agent_step} # replay ratio = 8
      iters: 1
  nets:
    encoder: impala[large,2]
    spectral_norm: last
    polyak: {every: 32e3, tau: 0.0}
  distq.enabled: false
  total: 40e6
  data.parallel: true
der:
  warmup: {n: 6.4e3, of: env_step}
  total: {n: 400e3, of: env_step}
  data:
    slice_len: 20
  opt:
    sched: {every: {n: 1, of: agent_step}}
    batch_size: 32
sample:
  ckpt: "runs/rainbow/ALE-Alien-v5__2024-03-21_11-45-42/ckpts/env_step=400004-val_ret=800.94.pth"
  mode: sample
  total: {n: 1e6, of: env_step}