_vars:
  act: &act elu
  norm: &norm none
  conv: &conv
    depth: &depth 48
    kernels: [4, 4, 4, 4]
    act: *act
    norm: *norm
  conv_t: &conv_t
    depth: *depth
    kernels: [5, 5, 6, 6]
    act: *act
    norm: *norm
  mlp: &mlp
    hidden: 400
    layers: 4
    act: *act
    norm: *norm
seed: 42
device: cuda
compute_dtype: float16
env:
  type: atari
  atari:
    env_id: Alien-v5
    screen_size: 64
    frame_skip: 4
    obs_type: grayscale
    noop_max: 30
    fire_reset: true
    term_on_life_loss: false
    time_limit: 108e3
    stack_num: ~
    use_envpool: true
wm:
  rssm:
    ensemble: 1
    deter_size: 1024
    stoch:
      type: discrete
      num_tokens: 32
      vocab_size: 32
    act: *act
    norm: *norm
    hidden_size: 1024
    jit: true
  opt:
    type: adam_w
    lr: 1e-4
    eps: 1e-5
    weight_decay: "${1e-6/lr}"
  kl:
    free: 0.0
    forward: false
    balance: 0.8
    free_avg: true
  reward_fn: tanh
  clip_rew: [-1.0, 1.0]
  coef: {}
  clip_grad: 1.0e2
  encoder:
    type: auto
    box: *mlp
    image: *conv
  decoders:
    obs:
      type: auto
      box:
        <<: [*mlp]
        dist: { type: mse }
      image:
        <<: [*conv_t]
        dist: { type: mse }
    reward:
      type: box
      <<: [*mlp]
      dist: { type: mse }
    term:
      type: discrete
      <<: [*mlp]
ac:
  actor: *mlp
  critic:
    <<: [*mlp]
    dist: { type: mse }
  target_critic: { every: 100 }
  opt:
    type: adam_w
    actor: { lr: 8e-5, weight_decay: "${1e-6/lr}" }
    critic: { lr: 2e-4, weight_decay: "${1e-6/lr}" }
    eps: 1e-5
  horizon: 15
  rew_norm:
    momentum: 1.0
    scale: 1.0
    eps: 1e-8
  gamma: 0.99
  gae_lambda: 0.95
  actor_grad: auto
  actor_grad_mix: 0.1
  actor_ent: 2e-3
  clip_grad: 1.0e2
  coef: {}
debug:
  deterministic: false
profile:
  enabled: false
  schedule: { wait: 5, warmup: 1, active: 3, repeat: 4 }
  functions: [_opt_step, take_env_step]
mode: train
train:
  dataset:
    capacity: 2e6
    batch_size: 16
    slice_len: 50
    subseq_len: [50, 50]
    prioritize_ends: true
    ongoing: false
  val_frac: 0.0
  num_envs: 1
  agent:
    expl_noise: 0.0
    eval_noise: 0.0
  prefill: 10e3
  total: 100e6
  opt_every: 5
  log_every: 16
