device: cuda
pred_layers: [500, 500, 500]
term_layers: [128]
rew_layers: [128]
act_layer: swish
num_particles: 20
num_models: 5
max_logvar: 1.0
min_logvar: -1.0
cem:
  pop: 100 # 400
  elites: 10 # 40
  horizon: 25
  niters: 5
  particles: 16
env:
  id: CartPole-v1
  type: classic
  reward: keep
  time_limit: null
  stack: null
  atari:
    noop_max: 30
    frame_skip: 4
    episodic_life: true
    grayscale: true
    screen_size: 84
    fire_reset: true
optim:
  type: adam
  lr: 3e-4
  eps: 1e-5
ensemble: 4
capacity: 100e3
total_steps: 100e3
env_steps: 512
batch_size: 128
replay_ratio: 64
profiler:
  enabled: false
  start:
    step: 0
  duration:
    step: 1