atari: &atari
  buffer:
    capacity: 500e3
    prefill: 20e3
  env:
    id: Alien-v4
    type: atari
    atari:
      noop_max: 30
      frame_skip: 4
      episodic_life: true
      grayscale: true
      screen_size: 84
      fire_reset: true
    reward: sign
    time_limit: null
    stack: 4
  value:
    target:
      sync_every: 8_000
      tau: 0.0
    opt:
      name: adam
      lr: 3e-4
      eps: 1e-4
  actor:
    opt:
      name: adam
      lr: 3e-4
      eps: 1e-4
  alpha:
    autotune: true
    ent_scale: 0.89
    value: null
  sched:
    total_steps: 5e6
    env_batch: 1
    opt_batch: 64
    value:
      opt_every: 4
      opt_iters: 1
    actor: ${value}
  exp:
    val_every: 25e3
  gamma: 0.99
cont: &cont
  buffer:
    capacity: 500e3
    prefill: 5e3
  env:
    id: Hopper-v4
    type: dmc
    reward: sign
  value:
    target:
      sync_every: 1
      tau: 0.995
    opt:
      name: adam
      lr: 1e-3
      eps: 1e-4
  actor:
    opt:
      name: adam
      lr: 3e-4
      eps: 1e-4
  alpha:
    autotune: true
    ent_scale: $(-1.0/math.log(2.0))
    value: null
  sched:
    total_steps: 1e6
    env_batch: 1
    opt_batch: 256
    value:
      opt_every: 1
      opt_iters: 1
    actor:
      opt_every: 2
      opt_iters: 2
  exp:
    val_every: 10e3
  gamma: 0.99
Alien-v4:
  <<: [*atari]
  env.id: AlienNoFrameskip-v4
Walker2d-v4:
  <<: [*cont]
  env.id: Walker2d-v4
  env.type: dmc