env:
  name: ALE/Alien-v5
  for_atari:
    screen_size: 84
    frame_stack: 4
    frame_skip: 4
    term_on_loss_of_life: true
    grayscale: true
    noop_max: 30
  reward_clip: [-1.0, 1.0]
  time_limit: 108e3
sched:
  num_frames: 10e6
  opt_batch: 256
  env_batch: 64
  replay_ratio: 8
  sync_q_every: 32e3
infra:
  device: gpu
  env_workers: 8
  gpu_batch: ${sched.opt_batch}
buffer:
  prefill: 80e3
  capacity: 1e6
encoder:
  type: impala
  variant: large/2
  spectral_norm: all
optimizer:
  name: adam
  lr: 2.5e-4
  eps: $(5e-3 / sched.opt_batch)
  grad_clip: 10.0
noisy_nets:
  enabled: true
  sigma0: 0.5
  factorized: true
multi_step:
  enabled: true
  n: 3
dist:
  enabled: false
  num_atoms: 51
  v_min: -10.0
  v_max: 10.0
pr:
  enabled: true
  alpha: 0.8
  beta: linear(0.45, 1.0, ${sched.num_frames})
gamma: 0.99
expl_eps: 0.0
decorr:
  enabled: true
  num_steps: auto
exp:
  val_every: 100e3
  val_episodes: 16
  val_envs: ${val_episodes}
  log_every: 1e3
profile:
  enabled: false
  wait: 3
  warmup: 2
  active: 5
  repeat: 4
  export_trace: true
  export_stack: true