random:
  seed: 1
  deterministic: false
device: cuda
env:
  type: gym
  gym:
    env_id: Ant-v4
total_steps: 1e6
num_envs: 1
batch_size: 256
log_sched: {every: [32, opt_step]}
warmup: 50e3
buf_cap: 1e6
gamma: 0.99
value:
  opt:
    type: adam
    lr: 1e-3
    eps: 1e-5
  polyak:
    sched: {every: [1, opt_step]}
    tau: 0.995
  sched: {every: [4, env_step]}
actor:
  opt:
    type: adam
    lr: 3e-4
    eps: 1e-5
  opt_ratio: 1
alpha:
  adaptive: true
  target_ent: auto
  value: 0.1
  opt: ${..value.opt}
hidden_dim: 256
val:
  envs: 4
  sched: {every: [32e3, env_step]}
  episodes: 32