env:
  id: Alien-v4
  type: atari
  atari:
    noop_max: 30
    frame_skip: 4
    episodic_life: true
    grayscale: true
    screen_size: 84
    fire_reset: true
  reward: sign
  time_limit: null
  stack: 1
  aug:
    enabled: true
sched:
  num_frames: 10e6
  opt_batch: 256
  env_batch: 64
  replay_ratio: 8
  sync_q_every: 32e3
infra:
  device: cuda
  env_workers: 8
  gpu_batch: ${sched.opt_batch}
buffer:
  prefill: 80e3
  capacity: 1e6
encoder:
  type: impala
  variant: large/2
  spectral_norm: all
optimizer:
  name: adam
  lr: 2.5e-4
  eps: ${5e-3 / sched.opt_batch}
  grad_clip: 10.0
  amp: bfloat16
noisy_nets:
  enabled: true
  sigma0: 0.5
  factorized: true
multi_step:
  enabled: true
  n: 3
dist:
  enabled: false
  num_atoms: 51
  v_min: -10.0
  v_max: 10.0
pr:
  enabled: true
  alpha: 0.8
  beta: linear(0.45, 1.0, ${sched.num_frames})
  eps: 1e-6
  batch_max: false
gamma: 0.99
expl_eps: 0.0
memory: 4
decorr:
  enabled: false
  num_steps: auto
exp:
  val_every: 100e3
  val_episodes: 16
  log_every: 128
profiler:
  enabled: false
  start:
    step: 100e3
  duration:
    step: 16
