env_id: AlienNoFrameskip-v4
seed: 1
torch_deterministic: true
cuda_deterministic: true
cuda: true
track: true
capture_video: false
total_timesteps: 10e6
learning_rate: 2.5e-4
num_envs: 8
num_steps: 128
anneal_lr: true
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 4
update_epochs: 4
norm_adv: true
clip_coef: 0.1
clip_vloss: true
ent_coef: 1e-2
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: null
batch_size: $(num_envs * num_steps)
minibatch_size: $(batch_size // num_minibatches)
wandb_project_name: cleanRL
wandb_entity: null
exp_name: null
custom_init: true