name: rsrch
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10.*
  - mamba=1.4.1
  - pytorch=2.0.*
  - torchvision=0.15.*
  - pytorch-cuda=11.7
  - pip=23.1.2
  - poetry=1.3.2
  - glew
platforms:
  - linux-64
variables:
  PYTHONNOUSERSITE: 1
