#!/usr/bin/bash -i
set -exo pipefail

cd "$(dirname "$0")"

conda-lock install --mamba -n rsrch
conda activate rsrch

find $CONDA_PREFIX -name direct_url.json -delete

source <(python ./_set_vars.py)

poetry install --with conda