device: cuda
env:
  type: atari
  atari:
    env_id: ALE/Alien-v5
    screen_size: [84, 84]
    frame_skip: 4
    obs_type: grayscale
    noop_max: 30
    fire_reset: True
    term_on_life_loss: True
    time_limit: 108e3
    stack: 4
distq:
  enabled: True
  num_atoms: 51
  v_min: -10.0
  v_max: +10.0
nets:
  enc_type: nature
  hidden_dim: 256
  dueling: True
  polyak: {every: 32e3}
data:
  buf_cap: 1e6
  slice_len: 4
total_steps: 10e6
num_envs: 8
noisy:
  enabled: True
  sigma0: 0.5
  factorized: true
aug:
  rew_clip: [-1.0, 1.0]
prioritized:
  enabled: True
  prio_exp: 0.5
  is_coef_exp: linear(0.4, 1.0, ${total_steps})
warmup: 5e3 # 25e3
val:
  sched: {every: 32e3}
  episodes: 32
opt:
  sched: {every: 32}
  batch_size: 256
  optimizer:
    type: adam
    lr: 2.5e-4
    eps: ${5e-3 / opt.batch_size}
  grad_clip: 10.0
log: {every: 128}
gamma: 0.99
dtype: float32