device: cuda
env:
  type: atari
  atari:
    env_id: ALE/Alien-v5
    screen_size: [84, 84]
    frame_skip: 4
    obs_type: grayscale
    noop_max: 30
    fire_reset: true
    term_on_life_loss: true
    time_limit: 108e3
    stack: 4
distq:
  enabled: true
  num_atoms: 51
  v_min: -10.0
  v_max: +10.0
nets:
  encoder: nature
  hidden_dim: 256
  dueling: true
  polyak: {every: [32e3, env_step], tau: 0.0}
  spectral_norm: false
data:
  buf_cap: 500e3
  slice_len: 3
  prefetch_factor: 2
  parallel: false
total_env_steps: 250e6
num_envs: 1
expl:
  noisy: true
  sigma0: 0.5
  factorized: true
  eps: 0.0
aug:
  rew_clip: [-1.0, 1.0]
prioritized:
  enabled: true
  prio_exp: 0.5
  is_coef_exp: linear(0.4, 1.0, ${total_env_steps})
warmup: 80e3
val:
  sched: {every: [128e3, env_step]}
  episodes: 32
opt:
  dtype: float32
  sched: {every: [4, agent_step]}
  batch_size: 32
  optimizer:
    type: adam
    lr: 2.5e-4
    eps: ${5e-3 / opt.batch_size}
  grad_clip: 10.0
log: {every: [16, opt_step]}
gamma: 0.99
double_dqn: true