faster:
  num_envs: 8
  prioritized:
    enabled: false
  # distq:
  #   enabled: false
debug:
  warmup: 2e3
  val.sched: {never: true}
  data.buf_cap: 100e3
der:
  warmup: 1.6e3
  data.slice_len: 20
  opt:
    sched: {every: 1}
    batch_size: 32