working:
  expl:
    noisy: true
    sigma0: 0.5
    eps: linear(1.0, 0.01, 500e3)
  prioritized:
    enabled: false
  total_env_steps: 10e6
  nets:
    encoder: impala[small]
    polyak: {every: [32.0e3, env_step]}
  opt:
    batch_size: 256
  distq:
    enabled: false
  data:
    parallel: true
debug:
  warmup: 2e3
  val.sched: {never: true}
  data.buf_cap: 100e3
der:
  warmup: 1.6e3
  data.slice_len: 20
  opt:
    sched: {every: 1}
    batch_size: 32