wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690371325.271674
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.10.10
      5: 0.15.5
      8:
      - 5
