#!/usr/bin/bash

filter_pkg() {
    name="$1"
    pkg="$2"

    err="$(poetry show "${name}" 2>&1 1>/dev/null)"
    if [[ ${#err} == 0 ]]; then
        echo $pkg
    fi
}

export -f filter_pkg

# Set up a clean conda env in order to get conda-installed packages
ENV_DIR="$(mktemp -d)"
conda-lock install -p "${ENV_DIR}" --mamba conda-lock.yml
conda activate "${ENV_DIR}"
find $CONDA_PREFIX -name direct_url.json -delete
$(python scripts/_fetch_vars.py)
conda activate ./env

pip freeze |\
    xargs python scripts/_parse_freeze.py |\
    parallel -n2 filter_pkg |\
    xargs poetry add --group conda --lock