#!/usr/bin/bash
set -o errexit

# Set up the conda env
conda-lock install -p ./env --mamba conda-lock.yml
conda activate ./env
# This fixes versions for conda-installed packages
find $CONDA_PREFIX -name direct_url.json -delete

# Set the environment variables from environment.yml
python scripts/_fetch_env_vars.py | xargs conda env config vars set
conda activate ./env

# Set up poetry stuff
pip install -r requirements.txt
poetry install
