device: cuda
random:
  seed: 42
  deterministic: true
env:
  type: gym
  gym:
    env_id: Walker2d-v4
  atari:
    env_id: ALE/Alien-v5
    screen_size: 84
    frame_skip: 4
    obs_type: grayscale
    noop_max: 30
    fire_reset: true
    term_on_life_loss: true
    time_limit: 108e3
    stack: 4
    use_envpool: true
buf_cap: 1e6
slice_len: 32